stages:
  get_data:
    cmd: python get_data.py
    deps:
    - get_data.py
    outs:
    - Wine.csv
  
  train:
    cmd: python kernel_pca.py
    deps:
    - kernel_pca.py
    - Wine.csv
    outs:
    - kernel_pca_test.png
    - kernel_pca_train.png
    metrics:
    - metrics_kernel_pca.txt:
        cache: false
  